/*1.Para cada titulación ordenar por coste mostrando primero las asignaturas más
caras y para las asignaturas del mismo coste mostrar por orden alfabético de
nombre de asignatura.
2. Mostrar el nombre y los apellidos de los profesores.*/
SELECT P.NOMBRE,P.APELLIDOS FROM PROFESOR p;
/*3. Mostrar el nombre de las asignaturas impartidas por profesores de Sevilla.*/
SELECT PP.NOMBRE FROM PROFESOR P, PERSONA PP
WHERE P.DNI= PP.DNI
AND PP.CIUDAD='SEVILLA';

SELECT P.NOMBRE FROM PERSONA P
INNER JOIN PROFESOR PP
ON PP.DNI=P.DNI
AND CIUDAD = 'SEVILLA';
/*4. Mostrar el nombre y los apellidos de los alumnos.*/
SELECT P.NOMBRE,P.APELLIDO FROM PERSONA P
INNER JOIN ALUMNO a
ON A.DNI = P.DNI;

SELECT P.NOMBRE, P.APELLIDO FROM PERSONA P,ALUMNO A
WHERE P.DNI=A.DNI;
/*5. Mostrar el DNI, nombre y apellidos de los alumnos que viven en Sevilla.*/
SELECT P.DNI,P.NOMBRE,P.APELLIDO FROM PERSONA P, ALUMNO A
WHERE P.DNI = A.DNI AND UPPER(P.CIUDAD) = 'SEVILLA';

SELECT P.DNI,P.NOMBRE,P.APELLIDO FROM PERSONA P
INNER JOIN ALUMNO A
ON P.DNI = A.DNI
AND upper(P.CIUDAD) = 'SEVILLA';
/*6. Mostrar el DNI, nombre y apellidos de los alumnos matriculados en la asignatura*/
/*"Seguridad Vial".*/
SELECT P.DNI, P.NOMBRE,P.APELLIDO FROM PERSONA P, ALUMNO A ,ALUMNO_ASIGNATURA AA
WHERE P.DNI=A.DNI AND A.IDALUMNO=AA.IDALUMNO AND AA.IDASIGNATURA =
'SEGURIDAD VIAL';
SELECT P.DNI,P.NOMBRE,P.APELLIDO FROM PERSONA P
INNEr JOIN ALUMNO A
ON P.DNI=A.DNI
INNER JOIN ALUMNO_ASIGNATURA AA
ON A.IDALUMNO=AA.IDALUMNO 
AND AA.IDASIGNATURA = 'SEGURIDAD VIAL';
/*7. Mostrar el Id de las titulaciones en las que está matriculado el alumno con DNI
20202020A. Un alumno está matriculado en una titulación si está matriculado en una
asignatura de la titulación.*/
SELECT T.IDTITULACION FROM TITULACION T
INNER JOIN ASIGNATURA A
ON T.IDTITULACION=A.IDTITULACION
INNER JOIN ALUMNO_ASIGNATURA AA
ON A.IDASIGNATURA=AA.IDASIGNATURA
INNER JOIN ALUMNO A2
ON AA.IDALUMNO = A2.IDALUMNO
AND A2.DNI='20202020A';

SELECT T.IDTITULACION FROM TITULACION T, ASIGNATURA A,
ALUMNO_ASIGNATURA AA, ALUMNO A2
WHERE T.IDTITULACION=A.IDTITULACION AND A.IDASIGNATURA=AA.IDASIGNATURA
AND AA.IDALUMNO=A2.IDALUMNO AND A2.DNI='20202020A';
/*8. Obtener el nombre de las asignaturas en las que está matriculada Rosa
Garcia*/.
SELECT distinct t.NOMBRE  
FROM ASIGNATURA t 
JOIN ALUMNO_ASIGNATURA aa 
ON aa.IDASIGNATURA = t.IDASIGNATURA 
JOIN ALUMNO a 
ON a.IDALUMNO = aa.IDALUMNO
JOIN PERSONA p 
ON p.DNI = a.DNI 
WHERE p.NOMBRE = 'Rosa'
AND p.APELLIDO ='Garcia';


/*9. Obtener el DNI de los alumnos a los que le imparte clase el profesor Jorge
Saenz.*/


SELECT distinct t.NOMBRE  
FROM ASIGNATURA t 
JOIN ALUMNO_ASIGNATURA aa 
ON aa.IDASIGNATURA = t.IDASIGNATURA 
JOIN PROFESOR a 
ON a.IDPROFESOR  = T.IDPROFESOR
JOIN PERSONA p 
ON p.DNI = a.DNI 
WHERE p.NOMBRE = 'JORGE'
AND p.APELLIDO ='SAENZ';


/*10. Obtener el DNI, nombre y apellido de los alumnos a los que imparte clase el
profesor Jorge Sáenz.*/
SELECT distinct p2.DNI,p2.NOMBRE,p2.APELLIDO 
FROM ASIGNATURA t 
JOIN ALUMNO_ASIGNATURA aa 
ON aa.IDASIGNATURA = t.IDASIGNATURA 
JOIN ALUMNO a 
ON a.IDALUMNO = aa.IDALUMNO
JOIN persona p2
ON p2.DNI = a.DNI 
JOIN PROFESOR pr
ON pr.IDPROFESOR = t.IDPROFESOR 
JOIN PERSONA p 
ON p.DNI = pr.DNI
WHERE p.NOMBRE = 'Jorge'
AND p.APELLIDO ='Saenz';

SELECT P2.DNI, P2.NOMBRE, P2.APELLIDO 
FROM PERSONA P2, ALUMNO A, ALUMNO_ASIGNATURA AA,
ASIGNATURA A2, PROFESOR P
WHERE P.DNI = A.DNI
AND A.IDALUMNO=AA.IDALUMNO
AND AA.IDASIGNATURA=A2.IDASIGNATURA
AND A2.IDPROFESOR=P.IDPROFESOR
AND P.DNI=P2.DNI
AND P2.NOMBRE = 'JORGE' AND P2.APELLIDO='SAENZ';
/*11. Mostrar el nombre de las titulaciones que tengan al menos una asignatura de 4
créditos.*/
SELECT T.NOMBRE FROM TITULACION T
INNER JOIN ASIGNATURA A
ON T.IDTITULACION=A.IDTITULACION
WHERE CREDITOS=4;

SELECT T.NOMBRE FROM TITULACION T, ASIGNATURA A
WHERE T.IDTITULACION=A.IDTITULACION AND CREDITOS=4;
/*12. Mostrar el nombre y los créditos de las asignaturas del primer cuatrimestre junto
con el nombre de la titulación a la que pertenecen.*/
SELECT AA.NOMBRE, AA.CREDITOS FROM ASIGNATURA AA
INNER JOIN TITULACION T
ON T.IDTITULACION=AA.IDTITULACION
WHERE AA.CUATRIMESTRE= 1;

SELECT AA.NOMBRE, AA.CREDITOS FROM ASIGNATURA AA, TITULACION T
WHERE T.IDTITULACION=AA.IDTITULACION AND AA.CUATRIMESTRE= 1;
/*13. Mostrar el nombre y el coste básico de las asignaturas de más de 4,5 créditos
junto con el nombre de las personas matriculadas*/
SELECT DISTINCT A.NOMBRE, A.COSTEBASICO,P.NOMBRE
FROM ASIGNATURA A
INNER JOIN ALUMNO A2
ON A2.IDALUMNO=A2.IDALUMNO
INNER JOIN PERSONA P
ON P.DNI=A2.DNI
WHERE A.CREDITOS >4.5;

SELECT A.NOMBRE, A.COSTEBASICO,P.NOMBRE
FROM ASIGNATURA A, ALUMNO A2,PERSONA P
WHERE A2.IDALUMNO=A2.IDALUMNO
AND P.DNI=A2.DNI AND A.CREDITOS > 4.5;
/*14. Mostrar el nombre de los profesores que imparten asignaturas con coste entre
25 y 35 euros, ambos incluidos*/
SELECT P.NOMBRE FROM PERSONA  P
INNER JOIN PROFESOR P2
ON P.DNI=P2.DNI
INNER JOIN ASIGNATURA A
ON P2.IDPROFESOR =A.IDPROFESOR
AND A.COSTEBASICO BETWEEN 25 AND 35;

SELECT P.NOMBRE FROM PERSONA P , PROFESOR P2 ,ASIGNATURA A
WHERE P.DNI=P2.DNI
AND P2.IDPROFESOR=A.IDPROFESOR
AND A.COSTEBASICO BETWEEN 25 AND 35;
/*15. Mostrar el nombre de los alumnos matriculados en la asignatura '150212' ó en la
'130113' ó en ambas.*/

SELECT P.NOMBRE FROM PERSONA P
INNER JOIN ALUMNO A
ON P.DNI=A.DNI
INNER JOIN ALUMNO_ASIGNATURA AA
ON A.IDALUMNO=AA.IDALUMNO
AND (AA.NUMEROMATRICULA = '150212' OR AA.NUMEROMATRICULA= '130113')
AND (AA.NUMEROMATRICULA = '150212' AND AA.NUMEROMATRICULA= '130113');

SELECT P.NOMBRE FROM PERSONA P, ALUMNO A , ALUMNO_ASIGNATURA AA
WHERE P.DNI=A.DNI
AND A.IDALUMNO=AA.IDALUMNO
AND AA.NUMEROMATRICULA IN ('150212','130113');
/*16. Mostrar el nombre de las asignaturas del 2º cuatrimestre que no sean de 6
créditos, junto con el nombre de la titulación a la que pertenece.*/
SELECT A.NOMBRE,T.NOMBRE FROM ASIGNATURA A
INNER JOIN TITULACION T
ON T.IDTITULACION = A.IDTITULACION
WHERE A.CUATRIMESTRE=2 AND A.CREDITOS!=6;

SELECT A.NOMBRE,T.NOMBRE FROM ASIGNATURA A,TITULACION T
WHERE T.IDTITULACION = A.TITULACION
AND A.CUATRIMESTRE=2 AND A.CREDITOS!=6;
/*17. Mostrar el nombre y el número de horas de todas las asignaturas. (1cred.=10
horas) junto con el dni de los alumnos que están matriculados.*/
SELECT A.NOMBRE, A.CREDITOS*10 "NUMERO_DE_HORAS", A2.DNI FROM ASIGNATURA a
JOIN ALUMNO_ASIGNATURA aa 
ON A.IDASIGNATURA = AA.IDASIGNATURA 
JOIN ALUMNO a2 
ON A2.IDALUMNO = AA.IDALUMNO;

SELECT A.NOMBRE, A.CREDITOS*10 "NUMERO_DE_HORAS", A2.DNI 
FROM ASIGNATURA a, ALUMNO_ASIGNATURA aa, ALUMNO a2  
WHERE  A.IDASIGNATURA = AA.IDASIGNATURA AND A2.IDALUMNO = AA.IDALUMNO;
/*18. Mostrar el nombre de todas las mujeres que viven en “Sevilla” y que estén
matriculados de alguna asignatura*/

SELECT P.NOMBRE FROM PERSONA P
INNER JOIN ALUMNO A
ON A.DNI = P.DNI
INNER JOIN ALUMNO_ASIGNATURA AA
ON A.IDALUMNO=AA.IDALUMNO
WHERE P.VARON = 0;

SELECT P.NOMBRE FROM PERSONA P , ALUMNO A, ALUMNO_ASIGNATURA AA
WHERE A.DNI = P.DNI
AND A.IDALUMNO=AA.IDALUMNO;
/*19. Mostrar el nombre de la asignatura de primero y que lo imparta el profesor con
identificador p101.*/
SELECT A.NOMBRE FROM ASIGNATURA A
INNER JOIN PROFESOR P
ON P.IDPROFESOR=A.IDPROFESOR
AND P.IDPROFESOR ='P101';

SELECT A.NOMBRE FROM ASIGNATURA A , PROFESOR P
WHERE P.IDPROFESOR=A.IDPROFESOR
AND P.ID='P101';
/*20. Mostrar el nombre de los alumnos que se ha matriculado tres o más veces en
alguna asignatura.*/
SELECT P.NOMBRE FROM PERSONA p 
JOIN ALUMNO a 
ON A.DNI = P.DNI 
JOIN ALUMNO_ASIGNATURA aa 
ON AA.IDALUMNO = A.IDALUMNO 
WHERE AA.NUMEROMATRICULA >=3;

SELECT P.NOMBRE 
FROM PERSONA p, ALUMNO a, ALUMNO_ASIGNATURA aa
WHERE AA.NUMEROMATRICULA >=3 AND AA.IDALUMNO = A.IDALUMNO 
AND A.DNI = P.DNI ;