CREATE TABLE DEPARTAMENTO
(
CODIGO NUMBER(10),
NOMBRE VARCHAR2(100),
PRESUPUESTO DECIMAL,
CONSTRAINT PK_DEPARTAMNETO PRIMARY KEY (CODIGO)
);

CREATE TABLE EMPLEADO 
(
CODIGO NUMBER(10),
NIF VARCHAR2(9),
NOMBRE VARCHAR2(100),
APELLIDO1 VARCHAR2(100),
APELLIDO2 VARCHAR2(100),
CODIGODEPARTAMENTO NUMBER(10),
CONSTRAINT PK_EMPLEADO PRIMARY KEY ( CODIGO),
CONSTRAINT FK1_EMPLEADO FOREIGN KEY ( CODIGODEPARTAMENTO) REFERENCES DEPARTAMENTO(CODIGO)
);



INSERT INTO DEPARTAMENTO VALUES(1,'DESARROLLO',120000,6000);
INSERT INTO DEPARTAMENTO VALUES(2,'SISTEMASA',150000,21000);
INSERT INTO DEPARTAMENTO VALUES(3,'RECURSOS HUMANOS',280000,25000);
INSERT INTO DEPARTAMENTO VALUES(4,'CONTABILIDAD',110000,3000);
INSERT INTO DEPARTAMENTO VALUES(5,'I+D',375000,380000 );
INSERT INTO DEPARTAMENTO VALUES(6,'PROYECTOS',0,0);
INSERT INTO DEPARTAMENTO VALUES(7,'PUBLICIDAD',0,1000);

INSERT INTO EMPLEADO VALUES(1,'32481596F','AARON','RIVERO','GOMEZ',1);
INSERT INTO EMPLEADO VALUES(2,'Y5575632D','ADELA','SALAS','DIAZ',2);
INSERT INTO EMPLEADO VALUES(3,'R6970642B','ADOLFO','RUBIO','FLORES',3);
INSERT INTO EMPLEADO VALUES(4,'77705545E','ADRIAN','SUAREZ',NULL,4);
INSERT INTO EMPLEADO VALUES(5,'17087203C','MARCOS','LOYOLA','MENDEZ',5);
INSERT INTO EMPLEADO VALUES(6,'38382980M','MARIA','SANTANA','MORENO',1);
INSERT INTO EMPLEADO VALUES(7,'80576669X','PILAR','RUIZ',NULL,2);
INSERT INTO EMPLEADO VALUES(8,'71651431Z','PEPE','RUIZ','SANTANA',3);
INSERT INTO EMPLEADO VALUES(9,'56399183D','JUAN','GOMEZ','LOPEZ',2);
INSERT INTO EMPLEADO VALUES(10,'46384486H','DIEGO','FLORES','SALAS',5);
INSERT INTO EMPLEADO VALUES(11,'67389283A','MARTA','HERRRERA','GIL',1);
INSERT INTO EMPLEADO VALUES(12,'41234836R','IRENE','SALAS','FLORES',NULL);
INSERT INTO EMPLEADO VALUES(13,'82635162B','JUAN ANOTNIO','SAEZ','GUERREO',NULL);

/*1) INSERTA DATOS EN DEPARTAMENTO CON SU NOMBRE, CODIGO,PRESUPUESTO*/
INSERT INTO DEPARTAMENTO VALUES(8,'MARKETING',120000,NULL);
/*2) INSERTA UN NUEVO DEPARTAMENTO SOLO CON NOMBRE Y PRESUPUESTO*/
INSERT INTO DEPARTAMENTO (CODIGO,NOMBRE) VALUES (9,'DISEÑO');
/*3* NUEVA COLUMNA*/
ALTER TABLE DEPARTAMENTO ADD GASTOS DECIMAL;
/*4 */
INSERT INTO EMPLEADO VALUES (14,'20504418E','FITO','FITI','PALDIS',8);
/*5
 * NO SE PUEDE REALIZAR DEBIDO A QUE EL CODIGO DEL EMPLEADO ES PRIMARY KEY
 * A NO SER QUE CREES UNA SENTENCIA DE AUTINCREMENT*/
CREATE SEQUENCE SQ_AUTOINCREMENT START WITH 15 INCREMENT BY 1;
INSERT INTO EMPLEADO VALUES(SQ_AUTOINCREMENT.NEXTVAL, '21514852F','LUCAS','SCANDE','IONE',8)

/*6*/
CREATE TABLE DEPARTAMENTO_BACKUP (
CODIGO NUMBER(10),
NOMBRE VARCHAR2(100),
PRESUPUESTO DECIMAL,
CONSTRAINT PK_DEPARTAMNETO_B PRIMARY KEY (CODIGO)
);
/*7
 * ES IMPOSIBLE ELIMINARLO PORQUE EN DEPARTAMENTO NO HAY NINGUN ATRIBUTO QUE SEA PROYECTOS
 * 
 * 8
 * ES IMPOSIBLE ELIMINARLO DEBIDO A QUE NO EXISTE EN LA TABLA DEPARTAMENTO UN ATRIBUTO 
 * CON ESE NOMBRE
 * 
 * 9
 * NO SE PEUDE ACTUALIZAR DEBIDO A QUE EL CODIGO QUE SE QUIERE ACTUALIZAR ES UNA CLAVE PRIMARIA.
 * 
 * 10
 *  * NO SE PEUDE ACTUALIZAR DEBIDO A QUE EL CODIGO QUE SE QUIERE ACTUALIZAR ES UNA CLAVE PRIMARIA.

11
 * */
UPDATE DEPARTAMENTO SET PRESUPUESTO = PRESUPUESTO + 50000 WHERE PRESUPUESTO<20000;
/*12*/
DELETE FROM EMPLEADO WHERE CODIGODEPARTAMENTO IS NULL;
SELECT * FROM EMPLEADO;
