CREATE TABLE DEPARTAMENTO
(
CODIGO NUMBER(10),
NOMBRE VARCHAR2(100),
PRESUPUESTO DECIMAL,
CONSTRAINT PK_DEPARTAMNETO PRIMARY KEY (CODIGO)
);

CREATE TABLE EMPLEADO 
(
CODIGO NUMBER(10),
NIF VARCHAR2(9),
NOMBRE VARCHAR2(100),
APELLIDO1 VARCHAR2(100),
APELLIDO2 VARCHAR2(100),
CODIGODEPARTAMENTO NUMBER(10),
CONSTRAINT PK_EMPLEADO PRIMARY KEY ( CODIGO),
CONSTRAINT FK1_EMPLEADO FOREIGN KEY ( CODIGODEPARTAMENTO) REFERENCES DEPARTAMENTO(CODIGO)
);


/*1) INSERTA DATOS EN DEPARTAMENTO CON SU NOMBRE, CODIGO,PRESUPUESTO*/
INSERT INTO DEPARTAMENTO VALUES(1,'DESARROLLO',120000);
/*2) INSERTA UN NUEVO DEPARTAMENTO SOLO CON NOMBRE Y PRESUPUESTO*/
INSERT INTO DEPARTAMENTO (CODIGO,NOMBRE) VALUES (2,'SISTEMAS');

/*3)*/
ALTER TABLE DEPARTAMENTO ADD GASTOS DECIMAL;

INSERT INTO DEPARTAMENTO VALUES(3,'Recursos Humanos',110000,3000);
INSERT INTO DEPARTAMENTO VALUES(4,'Contabilidad',120000,6000);
INSERT INTO DEPARTAMENTO VALUES(5,'I+D',375000,380000);
INSERT INTO DEPARTAMENTO VALUES(6,'Proyectos',0,0);
INSERT INTO DEPARTAMENTO VALUES(7,'Publicidad',0,1000);


