CREATE TABLE FABRICANTE 
(
CODIGO NUMBER(10),
NOMBRE VARCHAR2(100),
CONSTRAINT PK_FFABRICANTE PRIMARY KEY (CODIGO)
);

CREATE TABLE PRODUCTO 
(
CODIGO NUMBER(10),
NOMBRE VARCHAR2(100),
PRECIO DECIMAL,
CODIGO_FABRICANTE NUMBER(10),
CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO),
CONSTRAINT FK_PRODUCTO FOREIGN KEY (CODIGO_FABRICANTE) REFERENCES FABRICANTE(CODIGO)
);


INSERT INTO FABRICANTE VALUES (1,'ASUS');
INSERT INTO FABRICANTE VALUES (2,'LENOVO');
INSERT INTO FABRICANTE VALUES (3,'HEWLETT-PACKARD');
INSERT INTO FABRICANTE VALUES (4,'SAMSUNG');
INSERT INTO FABRICANTE VALUES (5,'SEAGATE');
INSERT INTO FABRICANTE VALUES (6,'CRUCIAL');
INSERT INTO FABRICANTE VALUES (7,'GIGABYTE');
INSERT INTO FABRICANTE VALUES (8,'HUAWEI');
INSERT INTO FABRICANTE VALUES (9,'XAOMI');

CREATE SEQUENCE SQ_AUTOINCREMENT START WITH 10 INCREMENT BY 1;
INSERT INTO FABRICANTE VALUES (SQ_AUTOINCREMENT.NEXTVAL,'ALCATEL');

INSERT S