CREATE TABLE FABRICANTE 
(
CODIGO NUMBER(10),
NOMBRE VARCHAR2(100),
CONSTRAINT PK_FFABRICANTE PRIMARY KEY (CODIGO)
);

CREATE TABLE PRODUCTO 
(
CODIGO NUMBER,
NOMBRE VARCHAR2(100),
PRECIO DECIMAL,
CODIGO_FABRICANTE NUMBER(10),
CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO),
CONSTRAINT FK_PRODUCTO FOREIGN KEY (CODIGO_FABRICANTE) REFERENCES FABRICANTE(CODIGO)
);


INSERT INTO FABRICANTE VALUES (1,'ASUS');
INSERT INTO FABRICANTE VALUES (2,'LENOVO');
INSERT INTO FABRICANTE VALUES (3,'HEWLETT-PACKARD');
INSERT INTO FABRICANTE VALUES (4,'SAMSUNG');
INSERT INTO FABRICANTE VALUES (5,'SEAGATE');
INSERT INTO FABRICANTE VALUES (6,'CRUCIAL');
INSERT INTO FABRICANTE VALUES (7,'GIGABYTE');
INSERT INTO FABRICANTE VALUES (8,'HUAWEI');
INSERT INTO FABRICANTE VALUES (9,'XAOMI');
INSERT INTO FABRICANTE (NOMBRE) VALUES ('Iphone');

CREATE SEQUENCE SQ_AUTOINCREMENT START WITH 2 INCREMENT BY 1;
INSERT INTO FABRICANTE VALUES (SQ_AUTOINCREMENT.NEXTVAL,'IPHONE');

SELECT * FROM FABRICANTE;
SELECT * FROM PRODUCTO;

INSERT INTO PRODUCTO VALUES (1,'DISCO DURO STA3 1TB',86.99,5);
INSERT INTO PRODUCTO VALUES (2,'MEMORIA RAM DDR4 8GB',120,6);
INSERT INTO PRODUCTO VALUES (3,'DISCO SSD 1 TB',150.99,4);
INSERT INTO PRODUCTO VALUES (4,'GEFORCE GTX 1050TI', 185,7);
INSERT INTO PRODUCTO VALUES (5,'GEFORCE GTX 1080 XTREME',755,6);
INSERT INTO PRODUCTO VALUES (6,'MONITOR 24 LED FULL HD', 202,1);
INSERT INTO PRODUCTO VALUES (7,'MONITOR 27 LED FULL HD',245.99,1);
INSERT INTO PRODUCTO VALUES (8,'PORTATIL YOGA 520', 559,2);
INSERT INTO PRODUCTO VALUES (9,'PORTATIL IDEAPD 320', 444,2);
INSERT INTO PRODUCTO VALUES (10,'IMPRESORA HP DESKJET 3720', 59.99,3);
INSERT INTO PRODUCTO VALUES (11,'IMPRESORA HP LASERJET PRO M26NW',180,3);

--ELIMINA EL FABRICANTE ASUS
DELETE FROM FABRICANTE WHERE NOMBRE LIKE 'ASUS';
--SI ES POSIBLE ELIMINARLO, PORQUE EL NOMBRE DEL FABRICANTE NO ES CLAVE PRIMARIA
DELETE FROM FABRICANTE WHERE NOMBRE LIKE 'XAOMI';
--SI ES POSIBLE PORQUE AL IGUAL QUE LA CUESTION ANTERIOR NO ES PRIMARY KEY 

--ACTUALIZAR EL CODIGO DE LENOVO
UPDATE FABRICANTE SET CODIGO=20 WHERE NOMBRE='LENOVO';
--SI ES POSIBLE 
UPDATE FABRICANTE SET CODIGO=30 WHERE NOMBRE LIKE 'HUAWEI';

UPDATE PRODUCTO SET PRECIO=PRECIO+5 ;

--ELIMINIA IMPRESORA PRECIO<200

DELETE FROM PRODUCTO WHERE NOMBRE LIKE 'IMPRESORA%' AND PRECIO<200;
