CREATE TABLE GAMAPRODUCTO
(
GAMA VARCHAR2(50),
DESCRIPCIONTEXTO CLOB,
DESCRIPCIOINHTML CLOB,
IMAGEN VARCHAR2(256),
CONSTRAINT PK_GAMAPRODCUTO PRIMARY KEY (GAMA)
);

CREATE TABLE PRODUCTO
(
CODIGOPRODUCTO VARCHAR2(15),
NOMBRE VARCHAR2(70),
GAMA VARCHAR2(50),
DIMENSIONES VARCHAR2(25),
PROVEEDOR VARCHAR2( 50),
DESCRIPCION CLOB,
CANTIDADENSTOK SMALLINT(6),
PRECIOVENTA DECIMAL(15,2),
PRECIOPROVEEDOR DECIMAL(15,2),
CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGOPRODUCTO),
CONSTRAINT FK1_PRODUCTO FOREIGN KEY ( GAMA) REFERENCES GAMAPRODUCTO(GAMA)
);

CREATE TABLE OFICINA
(
CODIGOOFICINA VARCHAR2(10),
CIUDAD VARCHAR2(50),
PAIS VARCHAR2(50),
REGION VARCHAR2(50),
CODIGOPOSTAL VARCHAR2(50),
TELEFONO VARCHAR2(20),
LINEADIRECCION1 VARCHAR2(50),
LINEADIRECCION2 VARCHAR2(50),
CONSTRAINT PK_EMPLEADO PRIMARY KEY (CODIGOOFICINA),
);


CREATE TABLE EMPLEADO
(
CODIGOEMPLEADO NUMBER(11),
NOMBRE VARCHAR2(50),
APELLIDO1 VARCHAR2(50),
APELLIDO2 VARCHAR2(50),
EXTENSION VARCHAR2(10),
EMAIL VARCHAR2(100),
CODIGO_OFICINA VARCHAR2(11),
CODIGOJEFE NUMBER(11),
PUESTO VARCHAR2(50),
CONSTRAINT PK_EMPLEADO PRIMARY KEY (CODIGOEMPLEADO),
CONSTRAINT FK1_EMPLEADO FOREIGN KEY (CODIGO_OFICNA) REFERENCES OFICINA(CODIGOOFICINA)
);

CREATE TABLE CLIENTE
(
CODIGOCLIENTE NUMBER(11),
NOMBRE_CLIENTE VARCHAR2(50),
NOMBRE_CONTACTO VARCHAR2(30),
APELLIDOCONTACTO VARCHAR(30),
TELEFONO VARCHAR2(15),
FAX VARCHAR2(15),
LINEADIRECCION1 VARCHAR2(50),
LINEADIRECCION2 VARCHAR2(50),
CIUDAD VARCHAR2(50),
REGION VARCHAR2(50),
PAIS VARCHAR2(50),
CODIGOPOSTAL VARCHAR2(10),
CODIGOEMPLEADO NUMBER(11),
LIMITECREDITO DECIMAL(15,2),
CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGOCLIENTE),
CONSTRAINT FK1_CLIENTE FOREIGN KEY (CODIGOEMPLEADO) REFERENCES EMPLEADO(CODIGOEMPLEADO)
);

CREATE TABLE PAGO
(
CODIGOCLIENTE NUMBER(11),
FORMADEPAGO VARCHAR2(40),
IDTRANSACCIONES VARCHAR2(50),
FECHAPAGO DATE,
TOTAL DECIMAL(15,2),
CONSTRAINT PK_PAGO PRIMARY KEY (CODIGOCLIENTE),
CONSTRAINT FK1_PAGO FOREIGN KEY (CODIGOCLIENTE) REFERENCES CLIENTE(CODIGOCLIENTE)
);

CREATE TABLE PEDIDO
(
CODIGOPEDIDO NUMBER(11),
FECHAPEDIDO DATE,
FECHAESPERADA DATE,
FECHAENTREGA DATE,
ESTADO VARCHAR2(15),
COMENTARIOS CLOB,
CODIGOCLIENTE NUMBER(11),
CONSTRAINT PK_PEDIDO PRIMARY KEY (CODIGOPEDIDO),
CONSTRAINT FK_PEDIDO FOREIGN KEY (CODIGOCLIENTE) REFERENCES CLIENTE(CODIGOCLIENTE)
);

CREATE TABLE DETALLEPEDIDO
(
CODIGOPEDIDO NUMBER(11),
CODIGOPRODUCTO VARCHAR2(15),
CANTIDAD NUMBER(11),
PRECIOUNIDAD DECIMAL(15,2),
NUMEROLINEA SMALLINT(6),
CONSTRAINT PK_DETALLEPEDIDO PRIMARY KEY (CODIGOPEDIDO,CODIGOPRODUCTO),
CONSTRAINT FK1_DETALLEPEDIDO FOREIGN KEY( CODIGOPEDIDO) REFERENCES PEDIDO(CODIGOPEDIDO),
CONSTRAINT FK2_DETALLEPDIDO FOREIGN KEY (CODIGOPRODUCTO) REFERENCES PRODUCTO(GAMAPRODUCTO)

);

