CREATE TABLE CLIENTE
(
NUMCLIENTE VARCHAR2(20),
SALDO VARCHAR2(20),
LIMCREDITO VARCHAR2(20),
DESCUENTO VARCHAR2(20)
);

CREATE TABLE DIRECCION
(
CODIRECCION VARCHAR2(20),
VIA VARCHAR2(20),
NOMBREVIA VARCHAR2(20),
NUMERO VARCHAR2(20),
PISO VARCHAR2(20),
PORTAL VARCHAR2(20),
CODPSTAL VARCHAR2(20)
);

CREATE TABLE POSEE
(
NUMCLIENTE VARCHAR2(20),
CODDIRECCION VARCHAR2(20)
);

CREATE TABLE PEDIDO
(
NUMPEDIDO VARCHAR2(20),
FECHA DATE,
NUMCLIENTE VARCHAR2(20),
CODDIRECCION VARCHAR2(20)
);

CREATE TABLE ARTICULO
(
NUMARTICULO VARCHAR2(20),
DESCRIPCION VARCHAR2(20)
);

CREATE TABLE FABRICA
(
NUMFABRICA VARCHAR2(20),
TELEFONO VARCHAR2(20)
);

CREATE TABLE DISTRIBUYE
(
NUMARTICULO VARCHAR2(29),
NUMFABRICA VARCHAR2(20),
CANTSUMINISTRO VARCHAR2(20),
EXISTENCIAS VARCHAR2(29)
);

CREATE TABLE INCLUYE 
(
NUMPEDIDO VARCHAR2(20),
NUMARTICULO VARCHAR2(20),
CANTIDAD VARCHAR2(20)
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (NUMCLIENTE);
ALTER TABLE DIRECCION ADD CONSTRAINT PK_DIRECCION PRIMARY KEY (CODDIRECCION);
ALTER TABLE POSEE ADD CONSTRAINT PK_POSEE PRIMARY KEY (NUMCLIENTE,CODDIRECCION);
ALTER TABLE POSEE ADD CONSTRAINT FK2_POSEE FOREIGN KEY (NUMCLIENTE) REFERENCES CLIENTE(NUNCLIENTE);
ALTER TABLE POSEE ADD CONSTRAINT FK1_POSEE FOREIGN KEY (CODDIRECCION) REFERENCES DIRECCION(CODDIRECCION);
ALTER TABLE PEDIDO ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMPEDIDO)
ALTER TABLE PEDIDO ADD CONSTRAINT FK1_PEDIDO FOREIGN KEY (NUMCLIENTE) REFERENCES CLIENTE(NUMCLIENTE);
ALTER TABLE PEDIDO ADD CONSTRAINT FK2_PEDIDO FOREIGN KEY (CODDIRECCION) REFERENCES DIRECCION(CODDIRECCION);
ALTER TABLE INCLUYE ADD CONSTRAINT PK_INCLUYE PRIMARY KEY (NUMPEDIDO,NUMARTICULO);
ALTER TABLE INCLUYE ADD CONSTRAINT FK1_INCLUYE FOREIGN KEY (NUMPEDIDO) REFERENCES PEDIDO(NUMPEDIDO);
ALTER TABLE INCLUYE ADD CONSTRAINT FK2_INCLUYE FOREIGN KEY (NUMARTICULO) REFERENCES ARTICULO(NUMARTICULO);
ALTER TABLE DISTRIBUYE ADD CONSTRAINT PK_DISTRIBUYE PRIMARY KEY (NUMARTICULO,NUMFBRICA);
ALTER TABLE ARTICULO ADD CONSTRAINT PK_ARTICULO PRIMARY KEY (NUMARTICULO);
ALTER TABLE FABRICA ADD CONSTRAINT PK_FABRICA PRIMARY KEY (NUMFABRICA);
ALTER TABLE DISTRIBUYE ADD CONSTRAINT FK1_DISTRIBUYE FOREIGN KEY (NUMARTICUO) REFERENCES ARTICULO(NUMARTICULO);
ALTER TABLE DISTRIBUYE ADD CONSTRAINT FK2_DISTRIBUYE FOREIGN KEY (NUMFABRICA) REFERENCES FABRICA(NUMFABRICA);


 