CREATE TABLE SUCURSAL
(
CODSUCURSAL VARCHAR2(20),
NOMBRE VARCHAR2(20),
DIRECCION VARCHAR2(20),
LOCALIDAD VARCHAR2(20)
);

CREATE TABLE CLIENTE
(
DNI VARCHAR2(20),
NOMBRE VARCHAR2(20),
DIRECCION VARCHAR2(20),
LOCALIDAD VARCHAR2(20)
);


CREATE TABLE TRANSACCION
(
CODSUCURSAL VARCHAR2(20),
CODCUENTA VARCHAR2(20),
NUMTRANSACCION VARCHAR2(20),
FECHA DATE,
CANTIDAD VARCHAR2(20),
TIPO VARCHAR2(20)
);

CREATE TABLE CUENTA
(
CODSUCURSAL VARCHAR2(20),
CODCUENTA VARCHAR2(20)
);

CREATE TABLE CLICUENTA
(
CODSUCURSAL VARCHAR2(20) AUTOINCREMET ,
CODCUENTA VARCHAR2 (20),
DNI VARCHAR2(20)
);

ALTER TABLE SUCURSAL ADD CONSTRAINT PK_SUCURSAL PRIMARY KEY (CODSUCURSAL);
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI);
ALTER TABLE CUENTA ADD CONSTRAINT PK_CUENTA PRIMARY KEY (CODSUCURSAL,CODCUENTA);
ALTER TABLE CUENTA ADD CONSTRAINT FK1_CUENTA FOREIGN KEY (CODSUCURSAL) REFERENCES SUCURSAL(CODSUCURSAL);
ALTER TABLE TRANSACCION ADD CONSTRAINT PK_TRANSACCION PRIMARY KEY (CODSUCURSAL,CODCUENTA,NUMTRANSACCION);
ALTER TABLE TRANSACCION ADD CONSTRAINT FK1_TRANSACCION FOREIGN KEY (CODSUCURSAL,CODCUENTA) REFERENCES CUENTA(CODSUCURSAL,CODCUENTA);
ALTER TABLE CLICUENTA ADD CONSTRAINT PK_CLICUENTA PRIMARY KEY (CODSUCURSAL,CODCUENTA,DNI);
ALTER TABLE CLICUENTA ADD CONSTRAINT FK1_CLICUENTA FOREIGN KEY (CODSUCURSAL,CODCUENTA) REFERENCES CUENTA(CODSUCURSAL,CODCUENTA);
ALTER TABLE CLICUENTA ADD CONSTRAINT FK2_CLICUENTA FOREIGN KEY (DNI) REFERENCES CLIENTE(DNI)