CREATE TABLE DIRECTOR
(
NOMBRE VARCHAR2 (20),
NACIONALIDAD VARCHAR2(20),
CONSTRAINT PK_DIRECTOR PRIMARY KEY (NOMBRE)
);

CREATE TABLE PELICULA
(
ID VARCHAR2(20),
TITULO VARCHAR2(20) NOT NULL,
PRODUCTORA VARCHAR2(20),
NACIONALIDAD VARCHAR2(20),
FECHA DATE,
DIRECTOR VARCHAR2(20),
CONSTRAINT PK_PELICULA PRIMARY KEY (ID),
CONSTRAINT FK_PELICULA FOREIGN KEY (DIRECTOR)REFERENCES DIRECTOR(NOMBRE)
);

CREATE TABLE ACTORES
(
NOMBRE VARCHAR2(20),
NACIONALIDAD VARCHAR2(20),
SEXO VARCHAR2(20),
CONSTRAINT PK_ACTORES PRIMARY KEY (NOMBRE),
CONSTRAINT CHECK1_ACTORES CHECK (SEXO IN ('H','M')
);

CREATE TABLE ACTUA
(
ACTOR VARCHAR2(20),
ID_PELI VARCHAR2(20),
PROTA VARCHAR2(20),
CONSTRAINT PK_ACTUA PRIMARY KEY (ACTOR,ID_PELI),
CONSTRAINT FK1_ACTUA FOREIGN KEY (ACTOR)  REFERENCES ACTORES(NOMBRE),
CONSTRAINT CHECK1_ACTUA CHECK (PROTA IN ('SI','NO'))
);

CREATE TABLE EJEMPLAR 
(
ID_PELI VARCHAR2(20),
NUMERO VARCHAR2(20),
ESTADO VARCHAR2(20),
CONSTRAINT PK_EJEMPLAR PRIMARY KEY (ID_PELI, NUMERO),
CONSTRAINT Fk_EJEMPLAR FOREIGN KEY (ID_PELI) REFERENCES PELICULA(ID)
);

CREATE TABLE SOCIO 
(
DNI VARCHAR2 (20),
NOMBRE VARCHAR2 (20) NOT NULL,
DIRECCION VARCHAR2(20),
TELEFONO VARCHAR2(9),
AVALADOR VARCHAR2(10),
CONSTRAINT PK_SOCIO PRIMARY KEY (DNI),
CONSTRAINT FK_SOCIO FOREIGN KEY (AVALADOR) REFERENCES SOCIO(DNI)
);

CREATE TABLE ALQUILA
(
DNI VARCHAR2(20),
ID_PELI VARCHAR2(20),
NUMERO VARCHAR2(20),
FECHAALQUILER DATE,
FECHADEVOLUCION DATE,
CONSTRAINT PK_ALQUILA PRIMARY KEY (DNI, ID_PELI, NUMERO, FECHAALQUILER),
CONSTRAINT FK1_ALQUILA FOREIGN KEY (DNI) REFERENCES SOCIO(DNI),
CONSTRAINT FK2_ALQUILA FOREIGN KEY (ID_PELI) REFERENCES EJEMPLAR(ID_PELI),
CONSTRAINT FK3_ALQUILA FOREIGN KEY (NUMERO) REFERENCES EJEMPLAR(NUMERO)
);