CREATE TABLE PERIODISTA
(
DNI VARCHAR2(20),
NOMBRE VARCHAR2(20),
DIRECCION VARCHAR2(20),
TELEFONO VARCHAR2(9),
ESPECIALISTA VARCHAR2(20),
CONSTRAINT PK_PERIODISTA PRIMARY KEY (DNI)
);

CREATE TABLE SUCURSAL 
(
CODIGO VARCHAR2(20),
DIRECCION VARCHAR2(20),
TELEFONO VARCHAR2(20),
CONSTRAINT PK_SUCURSAL PRIMARY KEY (CODIGO)
);

CREATE TABLE REVISTA 
(
NUMREG VARCHAR2(20),
TITULO VARCHAR2(20),
PERIODICIDAD VARCHAR2(20),
TIPO VARCHAR2(20),
SUCURSAL VARCHAR2(20),
CONSTRAINT PK_REVISTA PRIMARY KEY (NUMREG),
CONSTRAINT FK_REVISTA FOREIGN KEY (SUCURSAL) REFERENCES SUCURSAL(CODIGO)
);

CREATE TABLE EMPLEADO 
(
DNI VARCHAR2(20),
NOMBRE VARCHAR2(20),
DIRECCION VARCHAR2(20),
TELEFONO VARCHAR2(20),
SUCURSAL VARCHAR2(20),

CONSTRAINT PK_EMPLEADO PRIMARY KEY (DNI),
CONSTRAINT FK_EMPLEADO FOREIGN KEY (SUCURSAL) REFERENCES SUCURSAL(CODIGO)
);

CREATE TABLE ESCRIBE
(
NUMREG VARCHAR2(20),
DNI_PER VARCHAR2(20),
CONSTRAINT PK_ESCRIBE PRIMARY KEY (NUMREG,DNI_PER),
CONSTRAINT FK1_ESCRIBE FOREIGN KEY (NUMREG) REFERENCES REVISTA(NUMREG),
CONSTRAINT FK2_ESCRIBE FOREIGN KEY (DNI_PER) REFERENCES PERIODISTA(DNI)
);

CREATE TABLE NUMREVISTA
(
NUMREG VARCHAR2(20),
NUMERO VARCHAR2(20),
NUMPAGINAS VARCHAR2(20),
FECHA DATE,
CANTVENDIDAS VARCHAR2(20),
CONSTRAINT PK_NUMREVISTA PRIMARY KEY (NUMREG,NUMERO),
CONSTRAINT FK_NUMREVISTA FOREIGN KEY (NUMREG) REFERENCES REVISTA(NUMREG)
);