

CREATE TABLE MUNICIPIO
(
ID VARCHAR2(20),
NOMBRE VARCHAR2(20),
CODPOSTAL VARCHAR2(20),
CONSTRAINT PK_MUCNICIPIO PRIMARY KEY (ID)
);

CREATE TABLE VIVIENDA 
(
ID VARCHAR2(20),
TIPOVIA VARCHAR2(20),
NOMBREVIA VARCHAR2(20),
NUMERO VARCHAR2(20),
IDMUNICIPIO VARCHAR2(20),
CONSTRAINT PK_VIVIENDA PRIMARY KEY (ID),
CONSTRAINT FK_VIVIENDA FOREIGN KEY (IDMUNICIPIO) REFERENCES MUNICIPIO(ID)
);

CREATE TABLE PERSONA 
(
DNI VARCHAR2(20),
NOMBRE VARCHAR2(20),
FECHANAC DATE,
SEXO VARCHAR2(20),
IDVIVIENDA VARCHAR2(20),
CONSTRAINT PK_PERSONA PRIMARY KEY (DNI),
CONSTRAINT FK_PERSONA FOREIGN KEY (IDVIVIENDA) REFERENCES VIVIENDA(ID)
);

CREATE TABLE CABEZADEFAMILIA
(
DNI VARCHAR2(20),
IDVIVIENDA VARCHAR2(20) UNIQUE,
CONSTRAINT PK_CABEZADEFAMILIA PRIMARY KEY (DNI),
CONSTRAINT FK1_CABEZADEFAMILIA FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
CONSTRAINT FK2_CABEZADEFAMILIA FOREIGN KEY(IDVIVIENDA) REFERENCES VIVIENDA(ID)
);

CREATE TABLE POSEE
(
DNI VARCHAR2(20),
IDVIVIENDA VARCHAR2(20),
CONSTRAINT PK_POSEE PRIMARY KEY (DNI,IDVIVIENDA),
CONSTRAINT FK1_POSEE FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
CONSTRAINT FK2_POSEE FOREIGN KEY(IDVIVIENDA) REFERENCES VIVIENDA(ID)
);