CREATE TABLE CABALLOS 
(
CODCABALLOS VARCHAR2(4),
NOMBRE VARCHAR2(20) NOT NULL,
PESO NUMBER(3),
FECHANACIMINETO DATE,
PROPIETARIO VARCHAR2(25),
NACIONALIDAD VARCHAR2(20),
CONSTRAINT PK_CABALLOS PRIMARY KEY (CODCABALLOS),
CONSTRAINT CHECK1_CABALLOS CHECK (PESO BETWEEN  240 AND 300),
CONSTRAINT CHECK2_CABALLOS CHECK (NACIONALIDAD = UPPER(NACIONALIDAD))
);
 
INSERT INTO 

CREATE TABLE CARRERAS
(
CODCARRERA VARCHAR2(4),
FEHCAYHORA DATE,
IMPORTEPREMIO NUMBER(6),
APUESTALIMITE NUMBER(5,2),
CONSTRAINT PK_CARRERA PRIMARY KEY (CODCARRERA)

);

CREATE TABLE PARTICIPANTES
(
CODCABALLO VARCHAR2(4),
CODCARRERA VARCHAR2(4),
DORSAL VARCHAR2(25) NOT NULL,
JOCKEY VARCHAR2(20) NOT NULL,
POSICIONFINAL NUMBER(2),
CONSTRAINT PK_PARTICIPANTES PRIMARY KEY (CODCABALLO,CODCARRERA),
CONSTRAINT FK1_PARTICIPANTES FOREIGN KEY  (CODCABALLO) REFERENCES CABALLOS(CODCABALLOS),
CONSTRAINT FK2_PARTICIPANTES FOREIGN KEY (CODCARRERA) REFERENCES CARRERAS(CODCARRERA),
CONSTRAINT CHECK_PARTICIPANTES CHECK (POSICIONFINAL > 0)
);

CREATE TABLE CLIENTES 
(
DNI VARCHAR2(10),
NOMBRE VARCHAR2(20),
NACIONALIDAD VARCHAR2(20),
CONSTRAINT PK_CLIETNES PRIMARY KEY (DNI),

CONSTRAINT CHECK2_CLIENTES CHECK ( NACIONALIDAD = UPPER(NACIONALIDAD))
);

CREATE TABLE APUESTAS
(
DNICLIENTE VARCHAR2(10),
CODCABALLO VARCHAR2(4),
CODCARRERA VARCHAR2(4),
IMPORTE NUMBER(6) NOT NULL,
TANTOPORUNO NUMBER(4,2),
CONSTRAINT PK_APUESTAS PRIMARY KEY (DNICLIENTE,CODCABALLO,CODCARRERA),
CONSTRAINT FK1_APUESTAS FOREIGN KEY (CODCABALLO) REFERENCES CABALLOS(CODCABALLOS),
CONSTRAINT FK2_APUESTAS FOREIGN KEY (CODCARRERA) REFERENCES CARRERAS( CODCARRERA),
CONSTRAINT FK3_APUESTAS FOREIGN KEY (DNICLIENTE) REFERENCES CLIENTES (DNI),
CONSTRAINT CHECK1_APUESTAS CHECK (TANTOPORUNO>1)
);

/*2*/
INSERT INTO CLIENTES VALUES ('12145414L','MCCALISTER','ESCOCES');
INSERT INTO CABALLOS VALUES(1,'HERON',260,TO_DATE('12/04/2313','DD/MM/YYYY'),'VENTRUA','ESPAÑOLA' );
INSERT INTO CARRERAS c VALUES (1,TO_DATE('14/08/2014 10/30','DD/MM/YYYY HH24/MM'),1800,500);
INSERT INTO APUESTAS AS SELECT CODCARRERA FROM CARRERAS c  WHERE FECHAYHORA,IMPORTEPREMIO LIKE (TO_DATE('%D/[06-09]/2009'),2000);

/*3*/
INSERT INTO CABALLOS VALUES ('C6','`PERICO',260,TO_DATE('09/08/2023', 'DD/MM/YYYY '),'SOLOMAY','ARABE');
INSERT INTO PARTICIPANTES(CODCABALLO,CODCARRERA)  SELECT CODCABALLO FROM CABALLOS WHERE CODCABALLOS LIKE 'C6';

/*4*/


