CREATE TABLE CABALLOS 
(
CODCABALLOS VARCHAR2(4),
NOMBRE VARCHAR2(20) NOT NULL,
PESO NUMBER(3),
FECHANACIMINETO DATE,
PROPIETARIO VARCHAR2(25),
NACIONALIDAD VARCHAR2(20),
CONSTRAINT PK_CABALLOS PRIMARY KEY (CODCABALLOS),
CONSTRAINT CHECK1_CABALLOS CHECK (PESO BETWEEN  240 AND 300),
CONSTRAINT CHECK2_CABALLOS CHECK (NACIONALIDAD = UPPER(NACIONALIDAD))
);
 
 

CREATE TABLE CARRERAS
(
CODCARRERA VARCHAR2(4),
FECHAYHORA DATE,
IMPORTEPREMIO NUMBER(6),
APUESTALIMITE NUMBER(5,2),
CONSTRAINT PK_CARRERA PRIMARY KEY (CODCARRERA)

);
ALTER TABLE CARRERAS ADD CONSTRAINT CHECK1_CARRERAS CHECK(TO_CHAR(FEHCAYHORA,'HH24') BETWEEN 9 AND 13 OR TO_CHAR(FEHCAYHORA,'HH24') = 14 AND TO_CHAR(FEHCAYHORA,'MI')<30 );

CREATE TABLE PARTICIPANTES
(
CODCABALLO VARCHAR2(4),

CODCARRERA VARCHAR2(4),
DORSAL VARCHAR2(25) NOT NULL,
JOCKEY VARCHAR2(20) NOT NULL,
POSICIONFINAL NUMBER(2),
CONSTRAINT PK_PARTICIPANTES PRIMARY KEY (CODCABALLO,CODCARRERA),
CONSTRAINT FK1_PARTICIPANTES FOREIGN KEY  (CODCABALLO) REFERENCES CABALLOS(CODCABALLOS),
CONSTRAINT FK2_PARTICIPANTES FOREIGN KEY (CODCARRERA) REFERENCES CARRERAS(CODCARRERA),
CONSTRAINT CHECK_PARTICIPANTES CHECK (POSICIONFINAL > 0)
);

CREATE TABLE CLIENTES 
(
DNI VARCHAR2(10),
NOMBRE VARCHAR2(20),
NACIONALIDAD VARCHAR2(20),
CONSTRAINT PK_CLIETNES PRIMARY KEY (DNI),

CONSTRAINT CHECK2_CLIENTES CHECK ( NACIONALIDAD = UPPER(NACIONALIDAD))
);

CREATE TABLE APUESTAS
(
DNICLIENTE VARCHAR2(10),
CODCABALLO VARCHAR2(4),
CODCARRERA VARCHAR2(4),
IMPORTE NUMBER(6) NOT NULL,
TANTOPORUNO NUMBER(4,2),
CONSTRAINT PK_APUESTAS PRIMARY KEY (DNICLIENTE,CODCABALLO,CODCARRERA),
CONSTRAINT FK1_APUESTAS FOREIGN KEY (CODCABALLO) REFERENCES CABALLOS(CODCABALLOS),
CONSTRAINT FK2_APUESTAS FOREIGN KEY (CODCARRERA) REFERENCES CARRERAS( CODCARRERA),
CONSTRAINT FK3_APUESTAS FOREIGN KEY (DNICLIENTE) REFERENCES CLIENTES (DNI),
CONSTRAINT CHECK1_APUESTAS CHECK (TANTOPORUNO>1)
);


ALTER TABLE CABALLOS ADD CONSTRAINT CHECK3_CABALLOS CHECK ( EXTRACT (YEAR FROM FECHANACIMINETO) >2000);
/*2*/
INSERT INTO CLIENTES VALUES ('12145414L','MCCALISTER','ESCOCES');
INSERT INTO CABALLOS VALUES(1,'HERON',300,TO_DATE('12/04/2001','DD/MM/YYYY'),'VENTRUA','ESPAÑOLA' );
INSERT INTO CARRERAS c VALUES (1,TO_DATE('20/06/2009','DD/MM/YYYY'),2000,30);
INSERT INTO APUESTAS a VALUES ('12145414L',1,1,2000,30.1 );

/*3*/
INSERT INTO CABALLOS VALUES ('C6','PERICO',260,TO_DATE('09/08/2023', 'DD/MM/YYYY '),'SOLOMAY','ARABE');
INSERT INTO CARRERAS VALUES (12,TO_DATE('25/01/2026 12:20','DD/MM/YYYY HH24:MI'),2000,250);
INSERT INTO PARTICIPANTES p VALUES('C6',12,96,'SAN PEDRO',3) ;

/*4*/
INSERT INTO CARRERAS c VALUES(2,TO_DATE('22/01/2103 13:30','DD/MM/YYYY HH24:MI'),20000,540);
INSERT INTO CARRERAS c VALUES(4,TO_DATE('28/07/2103 14:10','DD/MM/YYYY HH24:MI'),200400,754);
/*5*/
ALTER TABLE CABALLOS DROP COLUMN PROPIETARIO;
/*6*/

UPDATE PARTICIPANTES SET JOCKEY =INITCAP( LOWER( JOCKEY));
ALTER TABLE PARTICIPANTES ADD CONSTRAINT CHECK2_PARTICIPANTES CHECK ( JOCKEY=INITCAP(JOCKEY));
INSERT INTO CABALLOS VALUES ('C2','PERICO',260,TO_DATE('09/08/2023', 'DD/MM/YYYY '),'SOLOMAY','ARABE');
INSERT INTO CARRERAS VALUES (8,TO_DATE('25/01/2026 12:20','DD/MM/YYYY HH24:MI'),2000,250);
INSERT INTO PARTICIPANTES p VALUES('C2',12,96,'SAN PEDRO',3) ;

ALTER TABLE CARRERAS ADD CONSTRAINT CHECK4_CARRERAS CHECK (TO_CHAR(FEHCAYHORA,'DD-MM') BETWEEN '10-05' AND '10-11');

ALTER TABLE CABALLOS ADD CONSTRAINT CHECK_14CABALLOS CHECK ( NACIONALIDAD IN ('ESPAÑOLA','ARABE','BRITANICA'));

UPDATE CARRERAS SET FEHCAYHORA = TO_DATE('06','MM');
/*6*/
/*NO PUEDO BORRAR LAS CARRERAS QUE NO HAYA CABALLO PORQUE DONDE APRACE EL CODCABALLOS ES PRIMARY KEY*/
/*7*/
ALTER TABLE CLIENTES ADD  CODIGO VARCHAR2(30) UNIQUE;

/*8*/
ALTER TABLE PARTICIPANTES DISABLE CONSTRAINT FK1_PARTICIPANTES;
ALTER TABLE APUESTAS DISABLE CONSTRAINT FK1_APUESTAS;
UPDATE CABALLOS SET CODCABALLOS = 'C66' WHERE CODCABALLOS ='C6';

ALTER TABLE APUESTAS ENABLE CONSTRAINT FK1_APUESTAS;
ALTER TABLE PARTICIPANTES ENABLE CONSTRAINT FK1_PARTICIPANTES;
/*9*/
ALTER TABLE APUESTAS ADD PREMIO VARCHAR2(30);
/*10*/
DROP TABLE APUESTAS;
DROP TABLE PARTICIPANTES;
DROP TABLE CLIENTES;
DROP TABLE CARRERAS;
DROP TABLE CABALLOS;

