CREATE TABLE EDITORIAL
(
CODEDITORIAL VARCHAR2(20),
DENOMINACION VARCHAR2(20)
);

CREATE TABLE TEMA
(
CODTEMA NUMBER(30),
DENOMINACION VARCHAR2(20),
CODTEMAPADRE VARCHAR2(20)
);

CREATE TABLE AUTOR 
(
CODAUTOR VARCHAR2(20),
NOMBRE VARCHAR2(20),
FNACIMIENTO DATE,
LIBROPRINCIPAL VARCHAR2(20)
);

CREATE TABLE LIBRO
(
CODLIBRO VARCHAR2(20),
TITULO VARCHAR2(20),
FCREACION DATE,
AUTORPRINCIPAL VARCHAR2(20)
);

CREATE TABLE LIBRO_AUTOR
(
CODLIBRO VARCHAR2(20),
CODAUTOR VARCHAR2(20),
ORDEN NUMBER(5)
);

CREATE TABLE PUBLICACIONES
(
CODEDITORIAL VARCHAR2(20),
CODLIBRO VARCHAR2(20),
PRECIO VARCHAR2(20),
FPUBLICACIONES DATE DEFAULT SYSDATE
);

ALTER TABLE EDITORIAL ADD CONSTRAINT PK_EDITORIAL PRIMARY KEY (CODEDITORIAL);
ALTER TABLE TEMA ADD CONSTRAINT PK_TEMA PRIMARY KEY (CODTEMA);
ALTER TABLE TEMA ADD CONSTRAINT FK1_TEMA FOREIGN KEY (CODTEMA) REFERENCES TEMA(CODTEMA);

ALTER TABLE LIBRO ADD CONSTRAINT PK_LIBRO PRIMARY KEY (CODLIBRO);

ALTER TABLE AUTOR ADD CONSTRAINT PK_AUTOR PRIMARY KEY (CODAUTOR);
ALTER TABLE AUTOR ADD CONSTRAINT FK1_AUTOR FOREIGN KEY (LIBROPRINCIPAL) REFERENCES LIBRO(CODLIBRO);

ALTER TABLE LIBRO ADD CONSTRAINT FK1_LIBRO FOREIGN KEY (AUTORPRINCIPAL) REFERENCES AUTOR(CODAUTOR);

ALTER TABLE LIBRO_AUTOR ADD CONSTRAINT PK_LIBROAUTOR PRIMARY KEY  (CODLIBRO,CODAUTOR);
ALTER TABLE LIBRO_AUTOR ADD CONSTRAINT FK1_LIBROAUTOR FOREIGN KEY (CODLIBRO) REFERENCES LIBRO(CODLIBRO);
ALTER TABLE LIBRO_AUTOR ADD CONSTRAINT FK2_LIBROAUTOR FOREIGN KEY (CODAUTOR) REFERENCES AUTOR(CODAUTOR);
ALTER TABLE PUBLICACIONES ADD CONSTRAINT PK_PUBLICACIONES PRIMARY KEY (CODEDITORIAL,CODLIBRO);
ALTER TABLE PUBLICACIONES ADD CONSTRAINT FK1_PUBLICACIONES FOREIGN KEY (CODLIBRO) REFERENCES LIBRO(CODLIBRO);
ALTER TABLE PUBLICACIONES ADD CONSTRAINT FK2_PUBLICACIONES FOREIGN KEY (CODEDITORIAL) REFERENCES EDITORIAL(CODEDITORIAL);



