CREATE TABLE VEHICULOS
(
MATRICULA VARCHAR2(7),
MARCA VARCHAR2 (10) NOT NULL,
MODELO VARCHAR2 (10) NOT NULL,
FECHACOMPRA DATE ,
PRECIOPORDIA NUMBER(2),
KILIMETROS VARCHAR(20)
);

CREATE TABLE CLIENTES
(
DNI VARCHAR(10),
NOMBRE VARCHAR(30) NOT NULL,
NACIONALIDAD VARCHAR2(30),
FECHANACIMIENTO DATE,
DIRECCION VARCHAR2(50)
);

CREATE TABLE ALQUILERES 
(
MATRICULA VARCHAR2(7) NOT NULL,
DNI VARCHAR2(10) NOT NULL,
FECHAHORA DATE,
NUMDIAS NUMBER(2) NOT NULL,
KILOMETROS NUMBER(4) DEFAULT (0)
);

ALTER TABLE VEHICULOS ADD CONSTRAINT PK_VEHICULOS PRIMARY KEY (MATRICULA);
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (DNI);
ALTER TABLE ALQUILERES ADD CONSTRAINT PK_ALQUILERES PRIMARY KEY (MATRICULA,DNI,FECHAHORA);
ALTER TABLE ALQUILERES ADD CONSTRAINT FK1_ALQUILERES FOREIGN KEY (MATRICULA) REFERENCES VEHICULOS(MATRICULA);
ALTER TABLE ALQUILERES ADD CONSTRAINT FK2_ALQUILERES FOREIGN KEY (DNI) REFERENCES CLIENTES(DNI);
ALTER TABLE VEHICULOS ADD CONSTRAINT CHECK1_VEHICULOS CHECK (FECHACOMPRA > TO_DATE('31/12/2001','DD/MM/YYYY' ));
ALTER TABLE VEHICULOS ADD CONSTRAINT CHECK2_VEHICULOS CHECK (PRECIOPORDIA >(0));