CREATE TABLE JUGADORES
(
CODJUGADOR VARCHAR2(4),
NOMBRE VARCHAR2(30) NOT NULL,
FECHANACIMIENTO DATE,
DEMARCACION VARCHAR2 (10),
CODEQUIPO VARCHAR2(4) 
);

CREATE TABLE EQUIPOS
(
CODEQUIPO VARCHAR2(4),
NOMBRE VARCHAR2(30) NOT NULL,
LOCALIDAD VARCHAR2(15)
);

CREATE TABLE PARTIDOS
(
CODPARTIDO VARCHAR2(4),
CODEQUIPOLOCAL VARCHAR2(4),
CODEQUIPOVISITANTE VARCHAR2(4),
FECHA DATE,
COMPETICION VARCHAR2(4),
JORNADA VARCHAR2(20)
);

CREATE TABLE INCIDENCIAS
(
NUMINCIDENCIA VARCHAR2(6),
CODPARTIDO VARCHAR2 (4),
CODJUGADOR VARCHAR2(4),
MINUTO NUMBER(2),
TIPO VARCHAR2(20)
);

ALTER TABLE JUGADORES ADD CONSTRAINT PK_JUGADORES PRIMARY KEY (CODJUGADOR) ;
ALTER TABLE EQUIPOS ADD CONSTRAINT PK_EQUIPOS PRIMARY KEY (CODEQUIPO);
ALTER TABLE PARTIDOS ADD CONSTRAINT PK_PARTIDOS PRIMARY KEY (CODPARTIDO);
ALTER TABLE INCIDENCIAS ADD CONSTRAINT PK_INCIDENCIAS PRIMARY KEY (NUMINCIDENCIA);
ALTER TABLE JUGADORES ADD CONSTRAINT FK_JUGADORES FOREIGN KEY (CODEQUIPO) REFERENCES EQUIPOS(CODEQUIPO);
ALTER TABLE PARTIDOS ADD CONSTRAINT FK1_PARTIDOS FOREIGN KEY (CODEQUIPOLOCAL) REFERENCES EQUIPOS(CODEQUIPO);
ALTER TABLE PARTIDOS ADD CONSTRAINT FK2_PARTIDOS FOREIGN KEY (CODEQUIPOVISITANTE) REFERENCES EQUIPOS(CODEQUIPO);
ALTER TABLE PARTIDOS ADD CONSTRAINT CHECK1_PARTIDOS FOREIGN KEY (PARTIDOS IN ('COPA', 'LIGA' ));
ALTER TABLE INCIDENCIAS ADD CONSTRAINT CHECK1_INCIDENCAIS CHECK (MINUTO BETWEEN (1 AND 100));
ALTER TABLE JUGADOR ADD CONSTRAINT CHECK1_JUGADOR CHECK (DEMARCACION =('PORTERO','DEFENSA','MEDIO''DELANTERO');
ALTER TABLE JUGADOR ADD CONSTRAINT CHECK2_JUGADOR CHECK (CODEQUIPO ~'^[0-9]');
ALTER TABLE JUGADOR ADD CONSTRAINT CHECK3_JUGADOR CHECK (NOMBRE ~'^[A-Z]');
















