CREATE TABLE BARCOS
(
MATRICULA VARCHAR2(20),
NOMBRE VARCHAR2(20),
CLASE VARCHAR2(20),
ARMARDOR VARCHAR2(20),
CAPACIDAD VARCHAR2(20),
NACIONALIDAD VARCHAR2(20),
CONSTRAINT PK_BARACOS PRIMARY KEY (MATRICULA),
CONSTRAINT CHECK_BARCOS CHECK (REGEXP_LIKE(MATRICULA,'^[A-Z]{2}-[1-9]{4}$'))
);

CREATE TABLE ESPECIE
(
CODIGO VARCHAR2(20),
NOMBRE VARCHAR2(20),
TIPO VARCHAR2(20),
CUPOPORBARCO VARCHAR2(20),
CALADEROPRINCIPAL VARCHAR2(20),
CONSTRAINT PK_ESPECIE PRIMARY KEY (CODIGO)
);

CREATE TABLE LOTES
(
CODIGO VARCHAR2(20),
MATRICULA VARCHAR2(20),
NUMKILOS VARCHAR2(20),
PRECIOPORKILOSALIDA VARCHAR2(20),
PRECIOPORKILOADJUNTADO VARCHAR2(20),
FECHAVENTA DATE NOT NULL,
CODESPECIE VARCHAR2(20),
CONSTRAINT PK_LOTES PRIMARY KEY (CODIGO),
CONSTRAINT FK1_LOTES FOREIGN KEY (MATRICULA) REFERENCES BARCOS(MATRICULA) ON DELETE CASCADE,
CONSTRAINT FK2_LOTES FOREIGN KEY (CODESPECIE) REFERENCES ESPECIE(CODIGO) ON DELETE CASCADE,
CONSTRAINT CHECK1_LOTES CHECK (PRECIOPORKILOADJUNTADO > PRECIOPORKILOSALIDA),
CONSTRAINT CHECK2_LOTES CHECK (NUMKILOS>0),
CONSTRAINT CHER3_LOTES CHECK(PRECIOPORKILOSALIDA>0)
);

CREATE TABLE CALADERO
(
CODIGO VARCHAR2(20),
NOMBRE VARCHAR2(20),
UBICACION VARCHAR2(20),
ESPECIEPRINCIPAL VARCHAR2(20),
CONSTRAINT PK_CALADERO PRIMARY KEY (CODIGO),
CONSTRAINT FK1_CALADERO FOREIGN KEY (ESPECIEPRINCIPAL) REFERENCES ESPECIE(CODIGO),
CONSTRAINT CHECK1_CALADERO CHECK (UPPER(NOMBRE) = NOMBRE),
CONSTRAINT CHECK2_CALADERO CHECK (UPPER(UBICACION) = UBICACION)
);

CREATE TABLE FECHASCAPTURAPERMITIDAS
(
CODESPECIE VARCHAR2(20),
CODCALADERO VARCHAR2(20),
FECHAINICIAL DATE,
FECHAFINAL DATE,
CONSTRAINT PK_FECHASCAPTURASPERMITIDAS PRIMARY KEY (CODESPECIE, CODCALADERO),
CONSTRAINT FK1_FECHASCAPTURAPERMITIDAS FOREIGN KEY (CODESPECIE) REFERENCES ESPECIE(CODIGO),
CONSTRAINT FK2_FECHASCAPTURAPERMITIDAS FOREIGN KEY (CODCALADERO) REFERENCES CALADERO(CODIGO),
CONSTRAINT CHECK3_FECHASCAPTURASPERMITIDAS CHECK ((TO_DATE(FECHAINICIAL 'DD/MM')) '02/02' OR (TO_DATE(FECHAFINAL 'DD/MM' )) '28/03')
);

ALTER TABLE ESPECIE ADD CONSTRAINT FK1_ESPECIE (CALADEROPRINCIPAL) REFERENCES CALADERO(CODIGO);
ALTER TABLE CALADERO ADD NOMBRECIENTIFICO;
ALTER TABLE BARCOS DROP COLUMN ARMADOR;
DROP TABLE ARMADOR;
DROP TABLE ESPECIE;
DROP TABLE LOTES;
DROP TABLE CALADERO; 

SELECT * FROM BARCOS;


