CREATE TABLE OFICINA 
(
CODIGO_OFICINA VARCHAR(10),
CIUDAD VARCHAR(30),
PAIS VARCHAR(50),
REGION VARCHAR(50),
CODIGOPOSTAL VARCHAR(10),
TELEFONO VARCHAR(20),
LINEADIRECCION1 VARCHAR(50),
LINEADIRECCION2 VARCHAR(50),
CONSTRAINT PK_OFICINA PRIMARY KEY (CODIGO_OFICINA)
);

CREATE TABLE EMPLEADO
(
CODIGO_EMPLEADO INT(11),
NOMBRE VARCHAR(50),
APELLIDO1 VARCHAR(50),
APELLIDO2 VARCHAR(50),
EXTENSION VARCHAR(50),
EMAIL VARCHAR(100),
CODIGO_OFICINA VARCHAR(10),
CODIGOJEFE INT(11),
PUESTO VARCHAR(50),
CONSTRAINT PK_EMPLEADO PRIMARY KEY (CODIGO_EMPLEADO),
CONSTRAINT FK1_EMPLEADO FOREIGN KEY (CODIGO_OFICINA) REFERENCES OFICINA(CODIGO_OFICINA),
CONSTRAINT FK2_EMPLEADO FOREIGN KEY (CODIGOJEFE) REFERENCES EMPLEADO(CODIGO_EMPLEADO)
);

CREATE TABLE CLIENTE
(
CODIGO_CLIENTE INT(11),
NOMBRECLIENTE VARCHAR(50),
NOMBRECONTACTO VARCHAR(30),
APELLIDOCONTACTO VARCHAR(30),
TELEFONO VARCHAR(50),
FAX VARCHAR(50),
LINEADIRECCION1 VARCHAR(50),
LINEADIRECCION2 VARCHAR(50),
CIUDAD VARCHAR(50),
REGION VARCHAR(50),
PAIS VARCHAR(50),
CODIGOPOSTAL VARCHAR(10),
CODIGOEMPLEADOREPVENTAS INT(11),
LIMITECREDITO DECIMAL(15,2),
CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO_CLIENTE),
CONSTRAINT FK1_CLIENTE FOREIGN KEY (CODIGOEMPLEADOREPVENTAS) REFERENCES EMPLEADO(CODIGO_EMPLEADO)
);

CREATE TABLE PAGO 
(
CODIGO_CLIENTE INT(11),
FORMADEPAGO VARCHAR(50),
ID_TRANSACCION VARCHAR(50),
FEHCADEPAGO DATE,
TOTAL DECIMAL (15,2),
CONSTRAINT PK_PAGO PRIMARY KEY (CODIGO_CLIENTE),
CONSTRAINT FK_PAGO FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE)
);

 CREATE TABLE PEDIDO 
 (
 CODIGOPEDIDO INT(11),
 FECHAPEDIDO DATE,
 FECHAESPERADA DATE,
 FECHAENTREGA DATE,
 ESTADO VARCHAR(15),
 COMENTARIOS TEXT,
 CODIGOCLIENTE INT(11),
 CONSTRAINT PK_PEDIDO PRIMARY KEY (CODIGOPEDIDO),
 CONSTRAINT FK1_PEDIDO FOREIGN KEY (CODIGOCLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE)
 );
 
 CREATE TABLE GAMAPRODUCTO
 (
 GAMA VARCHAR(50),
 DESCRIPCIONTEXTO TEXT,
 DESCRIPCIOHTML TEXT,
 IMAGEN VARCHAR(256),
 CONSTRAINT PK_GAMAPRODUCTO PRIMARY KEY (GAMA)
 );
 
 CREATE TABLE PRODUCTO
 (
 CODIGO_PRODUCTO VARCHAR(15),
 NOMBRE VARCHAR(70) UNIQUE,
 GAMA VARCHAR(50),
 DIMENSIONES VARCHAR(25),
 PROVEEDOR VARCHAR(50),
 DESCRIPCION TEXT,
 CANTIDADENSTOCK SMALLINT(6),
 PRECIOVENTA DECIMAL(15,2),
 PRECIOPROVEEDOR DECIMAL(15,2),
 CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO_PRODUCTO),
CONSTRAINT FK1_PRODUCTO FOREIGN KEY (GAMA) REFERENCES GAMAPRODUCTO(GAMA)
 );
 
 CREATE TABLE DETALLEPEDIDO
 (
 CODIGOPEDIDO INT(11),
 CODIGOPRODUCTO VARCHAR(15),
 CANTIDAD INT(11),
 PRECIOUNIDAD DECIMAL(15,2),
 NUMEROLINEA SMALLINT(6),
 CONSTRAINT PK_DETALLESPEDIDO PRIMARY KEY (CODIGOPEDIDO,CODIGOPRODUCTO),
 CONSTRAINT FK1_DETALLESPEDIDO FOREIGN KEY (CODIGOPEDIDO) REFERENCES PEDIDO(CODIGOPEDIDO)
);

ALTER TABLE PEDIDO ADD CONSTRAINT CHECK_FECHA_PEDIDO CHECK (FECHAPEDIDO<FECHAENTREGA);
ALTER TABLE PRODUCTO ADD CONSTRAINT CHECK_DIMENSIONES CHECK (DIMENSIONES>0);
ALTER TABLE OFICINA ADD CONSTRAINT CHECK_TELEFONO CHECK (TELEFONO="[0-9]");
ALTER TABLE PEDIDO ADD CONSTRAINT CHECK_PEDIDOD CHECK (ESTADO IN ('ENVIADO','EN TRANSITO') );
ALTER TABLE OFICINA MODIFY CODIGOPOSTAL INT(11);
ALTER TABLE PRODUCTO MODIFY DIMENSIONES INT(11);
ALTER TABLE CLIENTE ADD CONSTRAINT CHECK_NOMBRE ()

