--1
SELECT A.NOMBRE,A.APELLIDOS,A.TELF
FROM AFILIADOS A
WHERE EXTRACT(YEAR FROM A.NACIMIENTO)<1970;

--2
SELECT C.PESO,C.TALLA,C.PEZ
FROM CAPTURASSOLOS c 
WHERE C.TALLA <= 45
ORDER BY C.PEZ,C.PESO,C.TALLA;

--3
SELECT A.NOMBRE,A.APELLIDOS
FROM AFILIADOS A,PERMISOS P 
WHERE (A.FICHA = P.FICHA  AND (P.LICENCIA LIKE 'a%' OR P.LICENCIA LIKE 'A%' )) 
OR (A.TELF LIKE '9%' AND A.DIRECCION LIKE 'AVDA');

--4
SELECT DISTINCT L.LUGAR , L.CAUCE ,L.COMUNIDAD
FROM LUGARES L
INNER JOIN CAPTURASSOLOS c
ON L.LUGAR = C.LUGAR
AND C.PEZ LIKE 'Tenca';

--5
SELECT A.NOMBRE, A.APELLIDOS
FROM AFILIADOS A
INNER JOIN PARTICIPACIONES P
ON A.FICHA = P.FICHA 
AND TROFEO IS NOT NULL
INNER JOIN EVENTOS E
ON P.EVENTO = E.EVENTO
ORDER BY E.FECHA_EVENTO ASC;

--6
SELECT A.NOMBRE,A.APELLIDOS,A1.NOMBRE,A1.APELLIDOS
FROM AFILIADOS A
INNER JOIN CAPTURASSOLOS c  
ON A.FICHA = C.FICHA 
INNER JOIN AFILIADOS a1
ON C.AVAL2 = A1.FICHA;

--7
SELECT E.EVENTO
FROM EVENTOS E
INNER JOIN PARTICIPACIONES p 
ON E.EVENTO = P.EVENTO
AND P.FICHA LIKE '3,796'
AND EXTRACT(YEAR FROM E.FECHA_EVENTO)=1995
AND p.TROFEO IS NULL;

--8
SELECT DISTINCT  COUNT(C.PEZ)
FROM CAPTURASSOLOS c;

--9 
SELECT C.CAUCE
FROM LUGARES L, CAUCES c 
WHERE L.CAUCE = C.CAUCE
GROUP BY C.CAUCE
HAVING COUNT(L.CAUCE)>1;


--10
SELECT L.LUGAR
FROM LUGARES l,EVENTOS E
WHERE E.LUGAR IS NULL;

--11
SELECT COUNT(C1.PEZ) AS NUMERO_PECES,L.CAUCE
FROM LUGARES L, EVENTOS e, CAPTURASEVENTOS c1 
WHERE L.LUGAR = E.LUGAR 
AND e.EVENTO = C1.EVENTO
GROUP BY L.CAUCE 
ORDER BY  NUMERO_PECES DESC, L.CAUCE ;


--12
SELECT A.NOMBRE
FROM AFILIADOS a,CAPTURASSOLOS c 
WHERE A.FICHA = C.FICHA
GROUP BY A.NOMBRE
HAVING COUNT(C.LUGAR)>10;

--13
SELECT E.EVENTO
FROM EVENTOS E, PARTICIPACIONES p 
WHERE E.EVENTO =P.EVENTO
GROUP BY E.EVENTO 
HAVING COUNT(P.FICHA)>10;

--14

SELECT DISTINCT A.NOMBRE AS AVAL1, A1.NOMBRE AS AVAL2
FROM CAPTURASSOLOS c , AFILIADOS A, AFILIADOS A1
WHERE (C.AVAL1 = A.FICHA OR C.AVAL1 =A1.FICHA)
AND (C.AVAL2 = A.FICHA OR C.AVAL2 =A1.FICHA);

--15
SELECT A.NOMBRE, P.EVENTO
FROM AFILIADOS A
RIGHT JOIN PARTICIPACIONES p 
ON A.FICHA = P.FICHA;


--16
SELECT A.NOMBRE
FROM AFILIADOS a
INNER JOIN CAPTURASEVENTOS c 
ON A.FICHA = C.FICHA 
GROUP BY A.NOMBRE
HAVING COUNT(C.PEZ)=0
INTERSECT 
SELECT A.NOMBRE 
FROM AFILIADOS a 
INNER JOIN CAPTURASSOLOS c 
ON A.FICHA = C.FICHA
GROUP BY A.NOMBRE
HAVING COUNT(C.PEZ)=0;


--17
SELECT AVG(C.PESO)*COUNT(C.PEZ) AS MEDIA_PEZ, AVG(C.TALLA)*COUNT(C.PEZ) AS MEDIA_TALLA,A.NOMBRE
FROM CAPTURASSOLOS c, AFILIADOS A
GROUP BY A.NOMBRE;





















