CREATE TABLE PROFESOR
(
DNI VARCHAR2(30),
TITULACION VARCHAR2(30),
NOMBRE VARCHAR2(30),
APELLIDO1 VARCHAR2(30),
APELLIDO2 VARCHAR2(30),
GANA NUMBER(20),
DIRECCION VARCHAR2(30),
CONSTRAINT PK_PROFESOR PRIMARY KEY (DNI)
);



CREATE TABLE CURSOS
(
NOMBRE VARCHAR2(30),
CODIGO VARCHAR2(30),
DNI_PROFESOR VARCHAR2(30),
MAXIOMO_ALUMNOS NUMBER(20),
FECHA_INICIO DATE,
FECHA_FIN DATE,
NUME_HORAS NUMBER(20), 
CONSTRAINT PK_CURSO PRIMARY KEY ( CODIGO),
CONSTRAINT FK1_CURSO FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESOR(DNI)

);

CREATE TABLE ALUMNO
(
NOMBRE VARCHAR2(30),
APELLIDO1 VARCHAR2(30),
APELLIDO2 VARCHAR2(30),
DNI VARCHAR2(30),
DIRECCION VARCHAR2(30),
SEXO CHAR,
FECHA_NACIMINETO DATE,
CURSO VARCHAR2(30),
CONSTRAINT PK_ALUMNO PRIMARY KEY (DNI),
CONSTRAINT FK1_ALUMNO FOREIGN KEY (CURSO) REFERENCES CURSOS(CODIGO)
);

